import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.pandai.org/app/sign-in');
  await page.getByRole('textbox', { name: 'Email/Username' }).click();
  await page.getByRole('textbox', { name: 'Email/Username' }).fill('dianaadam2020');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('6FREEDOMhappy');
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: ' Quiz' }).click();
  await page.locator('div').filter({ hasText: 'English Grammar and Vocabulary' }).nth(4).click();
  await page.locator('#collapse-topic-19960').getByRole('link', { name: 'Start' }).click();
  await page.getByRole('radio', { name: 'who' }).check();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Next ' }).click();
  await page.locator('div').filter({ hasText: /^when$/ }).click();
  await page.getByRole('radio', { name: 'when' }).check();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Next ' }).click();
  await page.getByRole('radio', { name: 'that' }).check();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Next ' }).click();
  await page.getByRole('radio', { name: 'which' }).check();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Next ' }).click();
  await page.getByText('where', { exact: true }).click();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Submit Answer' }).click();
  await page.getByRole('link', { name: 'Practise new set' }).click();
  await page.getByRole('radio', { name: 'when' }).check();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Next ' }).click();
  await page.getByRole('radio', { name: 'when' }).check();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Next ' }).click();
  await page.locator('#quiz-item-112076').getByText('which', { exact: true }).click();
  await page.getByRole('radio', { name: 'which' }).check();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Next ' }).click();
  await page.getByRole('radio', { name: 'whom' }).check();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Next ' }).click();
  await page.getByRole('radio', { name: 'who', exact: true }).check();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Submit Answer' }).click();
  await page.getByRole('link', { name: 'Next topic' }).click();
  await page.getByRole('radio', { name: 'refuses' }).check();
  await page.getByRole('button', { name: 'Save Answer' }).click();
  await page.getByRole('button', { name: 'Submit Answer' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'Back to Quiz' }).click();
});
